"""add last_answer to tasks

Revision ID: 0780905f10ec
Revises: 2a6b4a9fa117
Create Date: 2026-06-30 12:54:48.835221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0780905f10ec'
down_revision: Union[str, Sequence[str], None] = '2a6b4a9fa117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('last_answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_answer')
    # ### end Alembic commands ###
